services:
  mysql:
    image: "mysql:9.7"
    environment:
      - "MYSQL_DATABASE=spring-commerce"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=api"
    ports:
      - "3306:3306"
