spring.application.name=spring-commerce
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring-commerce
spring.datasource.username=api
spring.datasource.password=secret
